name: Semgrep

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues
    # if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          auditOn: [push, pull_request]
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 2583
          generateSarif: "1"
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()
